# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
  - package-ecosystem: "maven"
    directory: "/rabbitmq"
    schedule:
      interval: "daily"
    target-branch: "main"
    ignore:
      - dependency-name: "ch.qos.logback:logback-classic"
        versions: [ "[1.3,)" ]
