name: Test
on:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-24.04
    container:
      image: pivotalrabbitmq/jepsen
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: last-execution.txt
      - name: Check last execution
        run: ci/check-last-execution.sh
      - uses: actions/upload-artifact@v4
        with:
          name: last-execution.txt
          path: last-execution.txt
